#!/bin/bash

echo ""
echo "🔐 Demo Login Credentials"
echo "========================="
echo ""
echo "Email:    demo@test.com"
echo "Password: Demo123456!"
echo ""
echo "📋 Additional Test Accounts:"
echo "   test@example.com / Test123456!"
echo ""
echo "🌐 Application URLs:"
echo "   Frontend: http://localhost:5173"
echo "   Login:    http://localhost:5173/login"
echo "   Backend:  http://localhost:3000"
echo "   API Docs: http://localhost:3000/api-docs"
echo ""
echo "✅ Both servers are running!"
echo ""
